### ISSUE TITLE
Crash when attempting to stream bangalore porch light

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#12]
```
06-11 08:42:36.947 18261-18397/com.zetta.android D/NoTils: [OkHttp http://stage.zettaapi.org/servers/bangalore/events?topic=light%2Fea246bad-f4d7-4b3f-a06c-88a0079998a2%2Fstate][(ZettaSdkApi.java:164).onUpdate] turning-on 
06-11 08:42:36.947 18261-18399/com.zetta.android E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                   Process: com.zetta.android, PID: 18261
                                                                   java.lang.IllegalArgumentException: Platform ? annotated [] requires explicit JsonAdapter to be registered
                                                                       at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:41)
                                                                       at com.squareup.moshi.Moshi.adapter(Moshi.java:94)
                                                                       at com.squareup.moshi.Moshi.adapter(Moshi.java:57)
                                                                       at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:51)
                                                                       at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:35)
                                                                       at com.squareup.moshi.Moshi.adapter(Moshi.java:94)
                                                                       at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:81)
                                                                       at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:65)
                                                                       at com.squareup.moshi.Moshi.adapter(Moshi.java:94)
                                                                       at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(AdapterMethodsFactory.java:212)
                                                                       at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:81)
                                                                       at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:33)
                                                                       at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:37)
                                                                       at com.apigee.zettakit.utils.ZIKJsonUtils.createObjectFromJson(ZIKJsonUtils.java:41)
                                                                       at com.apigee.zettakit.ZIKStream$2.onMessage(ZIKStream.java:128)
                                                                       at okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
                                                                       at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
                                                                       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
                                                                       at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
                                                                       at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
                                                                       at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
                                                                       at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
06-11 08:42:38.059 18261-18397/com.zetta.android D/NoTils: [OkHttp http://stage.zettaapi.org/servers/bangalore/events?topic=light%2Fea246bad-f4d7-4b3f-a06c-88a0079998a2%2Fstate][(ZettaSdkApi.java:164).onUpdate] on 

```

I get this crash on a 5.0.0 device, register for stream updates to the bangalore porch light. (doesn't happen for the thermometer, which the test is for)

**Comment by blundell** [comment]
Also a crash in the library should not crash the clients

**Comment by RobertWalsh** [comment]
Fixed this and added more robust exception handling within the project.
