### ISSUE TITLE
Stream error on close

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#22]
Sorry I can't reproduce this on request.

Sometimes when I go to close a stream I get an error:

```
                                                   Caused by: java.net.ProtocolException: unexpected end of stream
                                                               at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:384)
                                                               at okio.Buffer.writeAll(Buffer.java:993)
                                                               at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
                                                               at okhttp3.ResponseBody.bytes(ResponseBody.java:83)
                                                               at okhttp3.ResponseBody.string(ResponseBody.java:109)
                                                               at com.apigee.zettakit.ZIKSession.getDeviceWithLink(ZIKSession.java:231)
                                                               at com.apigee.zettakit.ZIKSession$6.call(ZIKSession.java:172)
                                                               at com.apigee.zettakit.ZIKSession$6.call(ZIKSession.java:168) 
                                                               at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:66) 
                                                               at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:172) 
                                                               at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:85) 
                                                               at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80) 
                                                               at rx.Subscriber.setProducer(Subscriber.java:211) 
                                                               at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76) 
                                                               at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99) 
                                                               at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:62) 
                                                               at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33) 
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) 
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
                                                               at rx.Observable.unsafeSubscribe(Observable.java:8460) 
                                                               at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) 
                                                               at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222) 
                                                               at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:818) 
                                                            Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.apigee.zettakit.ZIKLink.class
                                                               at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:70)
                                                               at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:172) 
                                                               at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:85) 
                                                               at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80) 
                                                               at rx.Subscriber.setProducer(Subscriber.java:211) 
                                                               at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76) 
                                                               at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99) 
                                                               at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:62) 
                                                               at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33) 
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) 
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
                                                               at rx.Observable.unsafeSubscribe(Observable.java:8460) 
                                                               at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) 
                                                               at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222) 
                                                               at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:818) 
```

Getting the error serverside might be ok, but I think it should be swallowed and not passed on to clients. (Clients don't care if the stream is failed to be closed, they just want to carry on).

**Comment by RobertWalsh** [comment]
Fixed here: https://github.com/zettaapi/zetta-sdk-android/commit/b1865a379826d00d66e902fd3c9b470ca6d029dd
