### ISSUE TITLE
transition fails on certain chars 

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#24]
If I change the test in https://github.com/zettaapi/zetta-sdk-android/blob/master/zettakit/src/androidTest/java/com/apigee/zettakit/TransitionTest.java called `testTransitionWithInput`

to this:
```
@Override
                                    public void onSuccess(@NonNull ZIKDevice result) {
                                        HashMap<String,Object> brightnessMap = new HashMap<>();
                                        final String newValue = "[foo]";// Math.random();
                                        brightnessMap.put("color", newValue);
                                        result.transition("set-color", brightnessMap,  new ZIKCallback<ZIKDevice>() {
                                            @Override
                                            public void onSuccess(@NonNull ZIKDevice device) {
                                                String updatedValue = String.valueOf(device.getProperties().get("color"));
                                                assertTrue(newValue.equals(updatedValue));
                                                signal.countDown();
                                            }
                                            @Override
                                            public void onFailure(@NonNull ZIKException exception) {
                                                throw new IllegalStateException("unexpected code path for this test");
                                            }
                                        });
                                    }
```

i.e. `String newValue = "[foo]"`

it fails with 
```
FATAL EXCEPTION: OkHttp Dispatcher
                                                                        Process: com.apigee.zettakit.test, PID: 6133
                                                                        java.lang.IllegalStateException: unexpected code path for this test
                                                                            at com.apigee.zettakit.TransitionTest$2$1$1$1.onFailure(TransitionTest.java:118)
                                                                            at com.apigee.zettakit.ZIKDevice$1.onResponse(ZIKDevice.java:134)
                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
```

**Comment by RobertWalsh** [comment]
Yea this kind of makes sense that it is returning an error.  

You are trying to set a color with `"[foo]"`... not sure what you expect it to do.

**Comment by blundell** [comment]
when I print out the current color it is `[255.0, 255.0, 255.0]` so I tried to change it to  `[254.0, 255.0, 255.0]` you see
