### ISSUE TITLE
testGet fails on a 4.2.2 device

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#5]
```
06-07 09:18:32.288 8251-8273/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:299)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:239)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                     at java.lang.Thread.run(Thread.java:856)
                                                  Caused by: com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was STRING at path $.properties at $.entities[1]
                                                     at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:86)
                                                     at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:75)
                                                     at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:52)
                                                     at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
                                                     at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:197)
                                                     at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:159)
                                                     at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
                                                     at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(AdapterMethodsFactory.java:213)
                                                     at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:81)
                                                     at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:33)
                                                     at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:37)
                                                     at com.apigee.zettakit.utils.ZIKJsonUtils.createObjectFromJson(ZIKJsonUtils.java:39)
                                                     at com.apigee.zettakit.tasks.ZIKServersAsyncTask.doInBackground(ZIKServersAsyncTask.java:56)
                                                     at com.apigee.zettakit.tasks.ZIKServersAsyncTask.doInBackground(ZIKServersAsyncTask.java:22)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                     at java.lang.Thread.run(Thread.java:856) 
```

Running the tests fails on a 4.2.2 genymotion emulator, but passes on a 5.0.0

**Comment by RobertWalsh** [comment]
A little more information could help.  Which server were you using?  If you could debug and find what URL `ZIKServersAsyncTask` is calling it would be very helpful.

**Comment by RobertWalsh** [comment]
Nevermind.  Figured out the issue.  This is fixed now.

**Comment by RobertWalsh** [comment]
I had a function that converted a `Map` to a JSON string.  

The code I was using that is broken in 4.2 but worked in 5.0 : 

     @NonNull
      public static String mapToJsonString(@NonNull final Map jsonMap) {
         return new JSONObject(jsonMap).toString();
      }

Seems that the `JSONObject.toString()` implementation is broken in the earlier versions when you have nested `Maps`.  

Looks as though the old version called the `Map.toString()` method instead of actually turning it into valid JSON where as the newer versions would convert those nested maps into valid JSON strings.

**Comment by blundell** [comment]
didn't know that 👍  nice find
